apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-deployment
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.17.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: "1048Mi"
          requests:
            cpu: 500m
            memory: "512Mi"
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.elk.svc.cluster.local:9200
        ports:
        - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kb-svc
  namespace: elk
  labels:
    app: kibana
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
