apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana8
  namespace: logging
  labels:
    app: kibana8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana8
  template:
    metadata:
      labels:
        app: kibana8
    spec:
      containers:
      - name: kibana
        image: kibana:8.9.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: "1048Mi"
          requests:
            cpu: 50m
            memory: "64Mi"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: '["http://camunda-8-elasticsearch.aurora:9200"]'
        ports:
        - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kb-svc
  namespace: logging
  labels:
    app: kibana8
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana8
  type: ClusterIP
