# Deployment file for crew aks demo
# https://discuss.elastic.co/t/unable-to-retrieve-version-information-from-elasticsearch-nodes/319776/7
# https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-deploy-kibana.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:8.10.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: "1048Mi"
          requests:
            cpu: 500m
            memory: "512Mi"
        # env:
        #   - name: ELASTICSEARCH_HOSTS
        #     value: '["https://elasticsearch-master.logging:9200"]'
        #   - name: ELASTICSEARCH_USERNAME
        #     value: elastic
        #   - name: ELASTICSEARCH_PASSWORD
        #     value: JbeiVCEreuLE7IO1
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: "config"
        configMap:
          name: kibana-config
      

---
apiVersion: v1
kind: Service
metadata:
  name: kb-svc
  namespace: logging
  labels:
    app: kibana
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP

# https://gist.github.com/chancez/048a8e5ec6f5049ee3f2356aac6fa1d4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
data:
  kibana.yml: |
    ---
    elasticsearch.hosts: ["https://elasticsearch-master.logging:9200"]
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: kibana_system
    elasticsearch.password: C52ZRgCzWvEQhtL22 # https://discuss.elastic.co/t/what-is-the-default-password-for-elasticsearch-8-alpha2/286119/2
    
