# Deployment file for crew aks demo
# https://discuss.elastic.co/t/unable-to-retrieve-version-information-from-elasticsearch-nodes/319776/7
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.17.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: "1048Mi"
          requests:
            cpu: 500m
            memory: "512Mi"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: '["http://elasticsearch-master.logging:9200"]'
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: JbeiVCEreuLE7IO1
        ports:
        - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kb-svc
  namespace: logging
  labels:
    app: kibana
spec:
  ports:
  - port: 80
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
