# Ref https://coralogix.com/blog/kubernetes-logging-with-elasticsearch-fluentd-and-kibana
apiVersion: v1
kind: Secret
metadata:
  name: es-credentials
type: Opaque
data:
  ES_USERNAME: elastic
  ES_PASSWORD: s5xPVCrChHQjhcRbvdi8
  
