# Ref https://coralogix.com/blog/kubernetes-logging-with-elasticsearch-fluentd-and-kibana
kind: Secret
apiVersion: v1
metadata:
  name: es-credentials
  namespace: logging
data:
  ELASTIC_USERNAME: ZWxhc3RpYw==
  ELASTIC_PASSWORD: czV4UFZDckNoSFFqaGNSYnZkaTg=
type: Opaque

  
