# https://artifacthub.io/packages/helm/elastic/elasticsearch/7.17.1
# 
replicas: 1
minimumMasterNodes: 1

esMajorVersion: "7"
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "7.9.1"
imagePullPolicy: "IfNotPresent"
nodeSelector:
  "kubernetes.io/os": linux

# esConfig:
#   elasticsearch.yml: |
#     xpack.security.enabled: true
#     xpack.security.transport.ssl.enabled: true
    # xpack.security.transport.ssl.verification_mode: certificate
    # xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    # xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12


secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/elasticsearch/config/certs

